#!/bin/bash

if [[ -z "$1" ]]
then
    > .gitignore
elif [[ "$1" = "help" ]]
then
    printf "\nGit Ignore\n\n"
    printf "Usage:\n"
    printf "    git ignore [OPTIONS]\n\n"
    printf "Options:\n"
    printf "    help - Print this help menu\n"
    printf "    list - List available templates\n"
    printf "    [NO OPTION] - Create empty gitignore\n"
    printf "    <TEMPLATE> - Create .gitignore template\n"
    printf "    <FILE> - Ignore local file\n\n"
elif [[ "$1" = "list" ]]
then
    gitignorer $1
elif [[ -e "$1" || -d "$1"  || -e "$(pwd)/$1" || -d "$(pwd)/$1" ]]
then
    if [[ ! -e .gitignore ]]
    then
        echo -e "$1" >> .gitignore
    elif [[ -z "$(grep -Fx "$1" .gitignore)" ]]
    then
        if [[ -z $(grep -Fx "# Custom Directories/Files" .gitignore) ]]
        then
            echo -e "# Custom Directories/Files" >> .gitignore
        fi
        echo -e "$1" >> .gitignore
    fi
elif [[ ! -z "'$(gitignorer list)' | grep -Fx '$1' > /dev/null" ]]
then
    if [[ -f .gitignore ]]
    then
        rm .gitignore
    fi
    gitignorer create $1
    echo -e "\n" >> .gitignore
fi
